service: sls-flask-lambda
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-southeast-1
  memorySize: 128
  environment:
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
    S3_BUCKET: ${env:S3_BUCKET}
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: src/app.app
package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!README.md'

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
